#include "hal_data.h"
#include "bsp_uart_debug.h"
#include "stdio.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

// 全局错误码变量
fsp_err_t err = FSP_SUCCESS;
// ADC转换完成标志
volatile bool scan_complete_flag = false;

// ADC回调函数，设置转换完成标志
void adc0_callback(adc_callback_args_t * p_args)
{
    // 宏将告知编译器回调函数不使用参数 p_args，从而避免编译器发出警告
    FSP_PARAMETER_NOT_USED(p_args);
    scan_complete_flag = true;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* 初始化调试串口 */
    uart_debug_init();

    /* 初始化ADC模块 */
    err = R_ADC_Open(&g_adc0_ctrl, &g_adc0_cfg);
    assert(FSP_SUCCESS == err); // 检查初始化是否成功

    /* 配置ADC通道 */
    err = R_ADC_ScanCfg(&g_adc0_ctrl, &g_adc0_channel_cfg);
    assert(FSP_SUCCESS == err);

    while (1)
    {
        uint16_t adc_data_ch5 = 0;   // 存储ADC通道5的原始数据
        double voltage_ch5;          // 存储转换后的电压值

        /* 启动ADC扫描 */
        (void)R_ADC_ScanStart(&g_adc0_ctrl);
        scan_complete_flag = false;
        while (!scan_complete_flag)
        {
            // 等待ADC转换完成（由回调函数置位）
        }

        /* 读取ADC通道5的转换结果 */
        err = R_ADC_Read(&g_adc0_ctrl, ADC_CHANNEL_5, &adc_data_ch5);
        assert(FSP_SUCCESS == err);

        /* 计算电压值，假设参考电压为3.3V，12位精度 */
        voltage_ch5 = (double)adc_data_ch5 / 4095.0 * 3.3;

        /* 打印ADC原始值和电压值到串口 */
        printf("P005(AN05)=%d, voltage=%.3fV \n", adc_data_ch5, voltage_ch5);

        /* 延时1秒 */
        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0
        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;
        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */
        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
#if BSP_CFG_SDRAM_ENABLED
        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable()
{
    // 空的非安全可调用模板函数
}
FSP_CPP_FOOTER

#endif
