#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

uint32_t gDir;
uint32_t gPulse;
uint32_t gStep;
uint32_t gPeriod;
timer_info_t gTimerInfo;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    g_timer2_pwm.p_api->open( g_timer2_pwm.p_ctrl, g_timer2_pwm.p_cfg);
    g_timer2_pwm.p_api->infoGet( g_timer2_pwm.p_ctrl, &gTimerInfo);
    gPeriod = gTimerInfo.period_counts;
    gStep = gPeriod/1000;
    g_timer2_pwm.p_api->start( g_timer2_pwm.p_ctrl);
    while(1)
    {

    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/***********************************************************************************************************************
* User-defined Functions
***********************************************************************************************************************/

/* PWM Timer Callback Function
 * Purpose: Adjusts PWM duty cycle based on timer events to create a breathing LED effect
 * Parameters: p_args - Timer callback arguments containing event type
 */
void timer2_pwm_callback(timer_callback_args_t *p_args)
{
    /* Adjust PWM duty cycle when timer cycle ends */
    if(p_args->event == TIMER_EVENT_CYCLE_END)
    {
        /* Adjust duty cycle based on direction */
        if(gDir)
            gPulse -= gStep;  // Decrease duty cycle
        else
            gPulse += gStep;  // Increase duty cycle

        /* Boundary check and direction reversal */
        if(gPulse <= 0)
            gDir = false;     // Reached minimum, reverse direction
        else if(gPulse >= gPeriod)
            gDir = true;      // Reached maximum, reverse direction

        /* Update PWM duty cycle */
        g_timer2_pwm.p_api->dutyCycleSet(g_timer2_pwm.p_ctrl, gPulse, GPT_IO_PIN_GTIOCB);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
